const CLUES =  [
    {
        id: '1',
        clue: 'Who invented the Python programming language?',
        answer: 'Guido van Rossum',
        value: 100,
    },
    {
        id: '2',
        clue: 'Windows, macOS, and Linux are examples of what?',
        answer: 'Operating systems',
        value: 100,
    },
    {
        id: '3',
        clue: 'What does GUI stand for?',
        answer: 'Graphical user interface',
        value: 100,
    },
    {
        id: '4',
        clue: 'What does the "JAM" in JAMStack stand for?',
        answer: 'JavaScript, APIs, and Markup',
        value: 200,
    },
    {
        id: '5',
        clue: 'What does CSS stand for?',
        answer: 'Cascading style sheets',
        value: 200,
    },
    {
        id: '6',
        clue: 'The number of bits in a "nibble"',
        answer: '4 (half a byte)',
        value: 200,
    },
    {
        id: '7',
        clue: 'Who wrote the first computer program?',
        answer: 'Ada Lovelace',
        value: 300,
    },
    {
        id: '8',
        clue: 'When was the world wide web invented?',
        answer: '1991',
        value: 300,
    },
    {
        id: '9',
        clue: 'What does RAM stand for?',
        answer: 'Random access memory',
        value: 300,
    },
    {
        id: '10',
        clue: 'Who wrote the first computer program?',
        answer: 'Ada Lovelace',
        value: 300,
    },
    {
        id: '11',
        clue: 'What does CSS stand for?',
        answer: 'Cascading style sheets',
        value: 200,
    },
    {
        id: '12',
        clue: 'What does GUI stand for?',
        answer: 'Graphical user interface',
        value: 100,
    },
    {
        id: '13',
        clue: 'Windows, macOS, and Linux are examples of what?',
        answer: 'Operating systems',
        value: 100,
    },
    {
        id: '14',
        clue: 'What does GUI stand for?',
        answer: 'Graphical user interface',
        value: 100,
    },
    {
        id: '15',
        clue: 'Windows, macOS, and Linux are examples of what?',
        answer: 'Operating systems',
        value: 100,
    },
    {
        id: '16',
        clue: 'Who invented the Python programming language?',
        answer: 'Guido van Rossum',
        value: 100,
    },
    {
        id: '17',
        clue: 'Who wrote the first computer program?',
        answer: 'Ada Lovelace',
        value: 300,
    },
    {
        id: '18',
        clue: 'Who invented the Python programming language?',
        answer: 'Guido van Rossum',
        value: 100,
    },
    {
        id: '19',
        clue: 'Windows, macOS, and Linux are examples of what?',
        answer: 'Operating systems',
        value: 100,
    },
    {
        id: '20',
        clue: 'What does GUI stand for?',
        answer: 'Graphical user interface',
        value: 100,
    },
    {
        id: '21',
        clue: 'What does the "JAM" in JAMStack stand for?',
        answer: 'JavaScript, APIs, and Markup',
        value: 200,
    },
    {
        id: '22',
        clue: 'What does CSS stand for?',
        answer: 'Cascading style sheets',
        value: 200,
    },
    {
        id: '23',
        clue: 'The number of bits in a "nibble"',
        answer: '4 (half a byte)',
        value: 200,
    },
    {
        id: '24',
        clue: 'Who wrote the first computer program?',
        answer: 'Ada Lovelace',
        value: 300,
    },
    {
        id: '25',
        clue: 'When was the world wide web invented?',
        answer: '1991',
        value: 300,
    },
    {
        id: '26',
        clue: 'What does RAM stand for?',
        answer: 'Random access memory',
        value: 300,
    },
    {
        id: '27',
        clue: 'Who wrote the first computer program?',
        answer: 'Ada Lovelace',
        value: 300,
    },
    {
        id: '28',
        clue: 'What does CSS stand for?',
        answer: 'Cascading style sheets',
        value: 200,
    },
    {
        id: '29',
        clue: 'What does GUI stand for?',
        answer: 'Graphical user interface',
        value: 100,
    },
    {
        id: '30',
        clue: 'Windows, macOS, and Linux are examples of what?',
        answer: 'Operating systems',
        value: 100,
    },
]

export default CLUES
